name: Phantom Dev dummy pipeline

on:
  push:
    branches:
      - "phantom"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: "${{ github.ref }}"

      - name: exec tests
        run: echo "reeee"